version: '3.8'

services:
  db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - auth_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      DATABASE_URL: postgres://postgres:123@db:5432/postgres?sslmode=disable
      JWT_SECRET: "secret"
      SERVER_ADDRESS: ":8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - auth_network

volumes:
  db_data:

networks:
  auth_network:
